backend:
  name: git-gateway
  branch: main # Replace with your default branch
media_folder: "static/images/uploads" # Where uploaded files will be stored
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
